/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path              = require('path');
const webpack           = require('webpack');
const webpackBase       = require('./webpack.base');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = webpackBase.init({
    // Add hot reloading in development
    entry: {
        main: {
            import: './src/app.js'
        }
    },
    output: {
        publicPath:    '/root/',
        filename:      '[name].[contenthash].js',
        chunkFilename: '[name].[contenthash].chunk.js',
    },

    plugins: [
        new HtmlWebpackPlugin({
            template: 'src/index.html',
            inject:   true, // Inject all files that are generated by webpack, e.g. bundle.js
            favicon:  'src/favicon.ico'
        }),
        new webpack.LoaderOptionsPlugin({
            debug: true
        })
    ],

    // Emit a source map for easier debugging
    devtool:      'eval-cheap-module-source-map',
    performance:  {hints: false},
    watch:        true,
    watchOptions: {
        poll:    1000, // Check for changes every second
        ignored: ['node_modules/**', 'server/**']
    }
});
